{% set name = "psiresp" %}
{% set version = "0.3.2" %}

package:
  name: psiresp-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e842cf5d662e788eb761cbde0c00ff35a732bb9ce7fd025a6063f90efdbe0563

build:
  number: 1

outputs:
  - name: psiresp-base
    
    build:
      noarch: python
    script: install_base.sh
    
    requirements:
      host:
        - python {{ python_min }}
        - pip
      run:
        - python >={{ python_min }}
        - qcelemental >=0.22.0
        - numpy
        - pydantic >=1.9
        - scipy >=1.4
        - tqdm
    
    test:
      requires:
        - python {{ python_min }}
      imports:
      - psiresp
      files:
        - test_basic_psiresp.py
      commands:
        - python test_basic_psiresp.py

  - name: psiresp
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
      run:
        - python >={{ python_min }},<3.10
        - geometric
        - rdkit
        - qcfractal >=0.15.8
        - requests
        - h5py <3.2
        - {{ pin_subpackage('psiresp-base', exact=True) }}
    
    test:
      requires:
        - python {{ python_min }}
      imports:
        - psiresp
      files:
        - test_rdkit_psiresp.py
      commands:
        - python test_rdkit_psiresp.py


about:
  home: https://github.com/lilyminium/psiresp
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Calculate RESP charges with Psi4'
  description: |
    PsiRESP is a package for calculating atomic partial charges
    from restrained and unrestrained electrostatic potential fits.
    The electrostatic potentials can be calculated using QCFractal
    and Psi4, or provided.
  doc_url: https://psiresp.readthedocs.io/
  dev_url: https://github.com/lilyminium/psiresp

extra:
  recipe-maintainers:
    - lilyminium
